/*
Copyright (c) 2008, George Blouin Jr. (skyhigh@solaris7.com)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are
permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of
conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list
of conditions and the following disclaimer in the documentation and/or other materials
provided with the distribution.
    * Neither the name of George Blouin Jr nor the names of contributors may be
used to endorse or promote products derived from this software without specific prior
written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

package dialog;

import java.awt.Cursor;
import java.io.File;
import java.io.IOException;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

import Force.*;
import Force.View.abTable;
import Force.View.tbBattleForce;
import Force.View.tbChatInfo;
import Force.View.tbTotalWarfareSmall;
import filehandlers.*;
import Print.*;
import IO.*;
import Print.preview.dlgPreview;
import battleforce.BattleForce;
import common.DataFactory;
import common.DesignForm;
import components.Mech;

import java.util.Vector;
import java.util.prefs.Preferences;


public class frmForce extends javax.swing.JFrame {
    private Force force = new Force();
    private Media media = new Media();
    private ImageTracker imageTracker;
    private DesignForm parent;
    private Preferences prefs = Preferences.userNodeForPackage("/ssw/gui/frmMain".getClass());

    private TableModelListener forceChanged = new TableModelListener() {
        public void tableChanged(TableModelEvent e) {
            getForce().setupTable(tblForce);
            lblTotalBV.setText(String.format("%1$,.0f", getForce().TotalAdjustedBV));
            lblTotalTons.setText(String.format("%1$,.0f", getForce().TotalTonnage) + " Tons");
            lblTotalUnits.setText(getForce().Units.size() + " Units");
        }
    };

    /** Creates new form frmForce */
    public frmForce( DesignForm Parent, ImageTracker imageTracker ) {
        initComponents();

        this.parent = Parent;
        this.imageTracker = imageTracker;

        force.setCurrentModel(new tbTotalWarfareSmall(force));
        force.addTableModelListener(forceChanged);
    }

    private void LoadMech() {
        try
        {
            Unit Data = (Unit) ((abTable) tblForce.getModel()).getForce().Units.get( tblForce.convertRowIndexToModel( tblForce.getSelectedRow() ) );
            Data.LoadMech();
            if ( Data.m != null ) {
                Vector u = new Vector();
                u.add(Data.m);
                parent.setUnit(u);
                parent.loadUnitIntoGUI();
                this.setVisible(false);
            } else {
                Media.Messager("Unable to load that 'Mech.");
            }

        } catch ( Exception e ) {
            Media.Messager(e.getMessage());
            System.out.println(e.getMessage());
        }
    }

    public void Add( Mech m ) {
        force.Units.add(new Unit(m));
    }








    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlbActions = new javax.swing.JToolBar();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnPrintForce = new javax.swing.JButton();
        btnPreview = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnExportMUL = new javax.swing.JButton();
        btnExportMTFs = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnAddMech = new javax.swing.JButton();
        btnRemoveUnit = new javax.swing.JButton();
        brnClearForce = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnAmmoChooser = new javax.swing.JButton();
        btnImages = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        cmbView = new javax.swing.JComboBox();
        spnList = new javax.swing.JScrollPane();
        tblForce = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTotalUnits = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPiloting = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtGunnery = new javax.swing.JTextField();
        lblTotalBV = new javax.swing.JLabel();
        lblTotalTons = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblForceName = new javax.swing.JLabel();
        txtForceName = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbUnitType = new javax.swing.JComboBox();

        setTitle("Force List");
        setMinimumSize(null);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tlbActions.setFloatable(false);
        tlbActions.setRollover(true);

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder-open-document.png"))); // NOI18N
        btnOpen.setToolTipText("Open Force");
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        tlbActions.add(btnOpen);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disk-black.png"))); // NOI18N
        btnSave.setToolTipText("Save Force");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        tlbActions.add(btnSave);
        tlbActions.add(jSeparator2);

        btnPrintForce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        btnPrintForce.setToolTipText("Print Force List");
        btnPrintForce.setFocusable(false);
        btnPrintForce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrintForce.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrintForce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintForceActionPerformed(evt);
            }
        });
        tlbActions.add(btnPrintForce);

        btnPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/projection-screen.png"))); // NOI18N
        btnPreview.setToolTipText("Preview");
        btnPreview.setFocusable(false);
        btnPreview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPreview.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        tlbActions.add(btnPreview);
        tlbActions.add(jSeparator1);

        btnExportMUL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document--arrow.png"))); // NOI18N
        btnExportMUL.setToolTipText("Export MUL");
        btnExportMUL.setFocusable(false);
        btnExportMUL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportMUL.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportMULActionPerformed(evt);
            }
        });
        tlbActions.add(btnExportMUL);

        btnExportMTFs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/documents--arrow.png"))); // NOI18N
        btnExportMTFs.setToolTipText("Export All to MTF");
        btnExportMTFs.setFocusable(false);
        btnExportMTFs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportMTFs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportMTFs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportMTFsActionPerformed(evt);
            }
        });
        tlbActions.add(btnExportMTFs);
        tlbActions.add(jSeparator3);

        btnAddMech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard--plus.png"))); // NOI18N
        btnAddMech.setToolTipText("Add Unit");
        btnAddMech.setFocusable(false);
        btnAddMech.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddMech.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddMech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMechActionPerformed(evt);
            }
        });
        tlbActions.add(btnAddMech);

        btnRemoveUnit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard--minus.png"))); // NOI18N
        btnRemoveUnit.setToolTipText("Remove Unit");
        btnRemoveUnit.setFocusable(false);
        btnRemoveUnit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemoveUnit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemoveUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUnitActionPerformed(evt);
            }
        });
        tlbActions.add(btnRemoveUnit);

        brnClearForce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard-empty.png"))); // NOI18N
        brnClearForce.setToolTipText("Clear Force List");
        brnClearForce.setFocusable(false);
        brnClearForce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        brnClearForce.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        brnClearForce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnClearForceActionPerformed(evt);
            }
        });
        tlbActions.add(brnClearForce);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-circle-double.png"))); // NOI18N
        btnRefresh.setToolTipText("Refresh Force List");
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        tlbActions.add(btnRefresh);
        tlbActions.add(jSeparator4);

        btnAmmoChooser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ammo.png"))); // NOI18N
        btnAmmoChooser.setFocusable(false);
        btnAmmoChooser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAmmoChooser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAmmoChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmmoChooserActionPerformed(evt);
            }
        });
        tlbActions.add(btnAmmoChooser);

        btnImages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images-stack.png"))); // NOI18N
        btnImages.setToolTipText("Manage Images");
        btnImages.setFocusable(false);
        btnImages.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImages.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagesActionPerformed(evt);
            }
        });
        tlbActions.add(btnImages);
        tlbActions.add(jSeparator5);

        jLabel4.setText("View:");
        tlbActions.add(jLabel4);

        cmbView.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Total Warfare", "BattleForce", "Information" }));
        cmbView.setMaximumSize(new java.awt.Dimension(100, 18));
        cmbView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViewActionPerformed(evt);
            }
        });
        tlbActions.add(cmbView);

        tblForce.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblForce.setGridColor(new java.awt.Color(204, 204, 204));
        tblForce.setRowMargin(2);
        tblForce.setShowVerticalLines(false);
        tblForce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblForceMouseClicked(evt);
            }
        });
        spnList.setViewportView(tblForce);

        lblTotalUnits.setText("0 Units");

        jLabel2.setText("P");

        txtPiloting.setText("5");
        txtPiloting.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPilotingFocusGained(evt);
            }
        });
        txtPiloting.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPilotingKeyReleased(evt);
            }
        });

        jLabel1.setText("G");

        txtGunnery.setText("4");
        txtGunnery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGunneryFocusGained(evt);
            }
        });
        txtGunnery.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGunneryKeyReleased(evt);
            }
        });

        lblTotalBV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalBV.setText("0 BV");

        lblTotalTons.setText("0 Tons");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(lblTotalTons, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGunnery, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPiloting, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalBV, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalUnits)
                    .addComponent(lblTotalBV)
                    .addComponent(lblTotalTons)
                    .addComponent(txtGunnery, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPiloting, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        lblForceName.setText("Force Name:");

        txtForceName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtForceNameFocusLost(evt);
            }
        });
        txtForceName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtForceNameKeyReleased(evt);
            }
        });

        lblLogo.setToolTipText("Unit Logo");
        lblLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        jLabel5.setText("Unit Type:");

        cmbUnitType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inner Sphere", "Clan", "Comstar / Word of Blake" }));
        cmbUnitType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnitTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblForceName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtForceName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUnitType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForceName)
                    .addComponent(txtForceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbUnitType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlbActions, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnList, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tlbActions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnList, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        force.RefreshBV();
    }//GEN-LAST:event_formWindowOpened

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        force.RefreshBV();
}//GEN-LAST:event_btnRefreshActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        force.RefreshBV();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tblForceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblForceMouseClicked
        if (evt.getClickCount() >= 2) { LoadMech(); }
    }//GEN-LAST:event_tblForceMouseClicked

    private void brnClearForceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnClearForceActionPerformed
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to clear the entire list?") == javax.swing.JOptionPane.YES_OPTION) {
            force.Clear();
            txtForceName.setText("");
            lblLogo.setIcon(null);
            cmbUnitType.setSelectedIndex(0);
        }
    }//GEN-LAST:event_brnClearForceActionPerformed

    private void btnRemoveUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUnitActionPerformed
        if ( tblForce.getSelectedRowCount() > 0 ) {
            int[] rows = tblForce.getSelectedRows();
            for ( int i=0; i < rows.length; i++ ) {
                Unit data = (Unit) force.Units.get(tblForce.convertRowIndexToModel(rows[i]));
                force.Units.remove(data);
            }
            force.RefreshBV();
        }
    }//GEN-LAST:event_btnRemoveUnitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if ( force.Units.size() > 0 ) {
            File saveFile = media.SelectFile(prefs.get("LastOpenForce", ""), "force", "Save To...");
            if ( saveFile != null ) {
                ForceWriter writer = new ForceWriter();
                try
                {
                    writer.SerializeForce(force, saveFile.getCanonicalPath());
                    prefs.put("LastOpenForce", saveFile.getCanonicalPath());
                    Media.Messager("Your force has been saved to " + saveFile.getCanonicalPath());
                } catch ( IOException ie ) {
                    Media.Messager(ie.getMessage());
                    System.out.println(ie.getMessage());
                }
            }
        } else {
            Media.Messager("You must add at least one unit before saving.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        File forceFile = media.SelectFile(prefs.get("LastOpenForce", ""), "force", "Load Force List");
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        DataReader reader = new DataReader();
        if ( forceFile != null ) {
            try {
                force = new Force(reader.ReadNode(forceFile.getCanonicalPath(), "force"));
                force.addTableModelListener(forceChanged);
                txtForceName.setText(force.ForceName);
                if ( force.getType().equals(BattleForce.InnerSphere) ) {
                    cmbUnitType.setSelectedIndex(0);
                } else if ( force.getType().equals(BattleForce.Clan) ) {
                    cmbUnitType.setSelectedIndex(1);
                } else {
                    cmbUnitType.setSelectedIndex(2);
                }
                media.setLogo(lblLogo, new File(force.LogoPath));
                force.RefreshBV();
                prefs.put("LastOpenForce", forceFile.getCanonicalPath());
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
                Media.Messager("Could not open force.\n" + ex.getMessage());
            }
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnPrintForceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintForceActionPerformed
        Scenario scenario = new Scenario(force);
        dlgPrint print = new dlgPrint(this, true, scenario, imageTracker);
        print.setLocationRelativeTo(this);
        print.setVisible(true);
    }//GEN-LAST:event_btnPrintForceActionPerformed

    private void btnExportMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportMULActionPerformed
        MULWriter mw = new MULWriter(force);
        File mulFile = media.SelectFile( prefs.get( "MTFExportPath", "" ), "mul", "Select MUL file" );
        try {
            String filename = mulFile.getCanonicalPath();
            if ( ! filename.endsWith(".mul") ) { filename += ".mul"; }
            mw.Write(filename);
            Media.Messager(filename + " saved.");
        } catch (IOException ex) {
            Media.Messager("Could not export MUL file.\n" + ex.getMessage());
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnExportMULActionPerformed

    private void btnAddMechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMechActionPerformed
        parent.showOpenDialog();
}//GEN-LAST:event_btnAddMechActionPerformed

    private void btnExportMTFsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportMTFsActionPerformed
        String  error = "",
                filename = "";
        MTFWriter mtf = new MTFWriter();
        String mtfDir = media.GetDirectorySelection(null, prefs.get( "MTFExportPath", "" ) );
        if (!mtfDir.endsWith(File.separator)) { mtfDir += File.separator; }
        
        for ( int i = 0; i < force.Units.size(); i++ ) {
            Unit u = (Unit) force.Units.get(i);
            u.LoadMech();
            mtf.setMech(u.m);
            try {
                filename = mtfDir + u.m.GetFullName() + ".mtf";
                mtf.WriteMTF(filename);
            } catch (IOException ie) {
                System.out.println(ie.getMessage());
                error += "Attempted " + filename + ": " + ie.getMessage() + "\n";
            }
        }
        
        if ( !error.isEmpty() ) {
            Media.Messager(error);
        } else {
            Media.Messager("All units have been saved to MTF.");
        }
    }//GEN-LAST:event_btnExportMTFsActionPerformed

    private void txtGunneryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGunneryKeyReleased
        if ( !txtGunnery.getText().isEmpty() ) {
            for ( int i = 0; i < force.Units.size(); i++ ) {
                Unit u = (Unit) force.Units.get(i);
                u.setGunnery(Integer.parseInt(txtGunnery.getText()));
                u.Refresh();
            }
            force.RefreshBV();
        }
    }//GEN-LAST:event_txtGunneryKeyReleased

    private void txtPilotingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPilotingKeyReleased
        if ( !txtPiloting.getText().isEmpty() ) {
            for ( int i = 0; i < force.Units.size(); i++ ) {
                Unit u = (Unit) force.Units.get(i);
                u.setPiloting(Integer.parseInt(txtPiloting.getText()));
                u.Refresh();
            }
            force.RefreshBV();
        }
    }//GEN-LAST:event_txtPilotingKeyReleased

    private void txtGunneryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGunneryFocusGained
        txtGunnery.selectAll();
    }//GEN-LAST:event_txtGunneryFocusGained

    private void txtPilotingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPilotingFocusGained
        txtPiloting.selectAll();
    }//GEN-LAST:event_txtPilotingFocusGained

    private void btnAmmoChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmmoChooserActionPerformed
        if ( tblForce.getSelectedRowCount() > 0 ) {
            int[] rows = tblForce.getSelectedRows();
            for ( int i=0; i < rows.length; i++ ) {
                try {
                    Unit data = (Unit) force.Units.get( tblForce.convertRowIndexToModel( rows[i] ) );
                    data.LoadMech();
                    if ( data.m != null ) {
                        dlgAmmoChooser Ammo = new dlgAmmoChooser( this, false, data.m, new DataFactory(data.m) );
                        Ammo.setLocationRelativeTo( this );
                        if( Ammo.HasAmmo() ) {
                            Ammo.setVisible( true );
                        } else {
                            Media.Messager("This 'Mech has no ammunition to exchange." );
                            Ammo.dispose();
                        }
                    } else {
                        Media.Messager("The 'Mech could not be loaded from " + data.Filename + ", cannot adjust ammo.");
                    }
                } catch( Exception e ) {
                    Media.Messager("There was an error altering the ammunition on this 'Mech:\n" + e.getMessage() );
                }
            }
        }
    }//GEN-LAST:event_btnAmmoChooserActionPerformed

    private void txtForceNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtForceNameFocusLost
        force.ForceName = txtForceName.getText();
    }//GEN-LAST:event_txtForceNameFocusLost

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        PagePrinter printer = new PagePrinter();
        printer.setJobName(force.ForceName);
        Scenario scenario = new Scenario(force);

        //Force List
        ForceListPrinter sheet = new ForceListPrinter(imageTracker);
        sheet.AddForce(force);
        printer.Append( BFBPrinter.Letter.toPage(), sheet );

        dlgPreview prv = new dlgPreview("Print Preview", this, printer, scenario, imageTracker);
        prv.setLocationRelativeTo(this);
        prv.setVisible(true);
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void txtForceNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtForceNameKeyReleased
        force.ForceName = txtForceName.getText();
    }//GEN-LAST:event_txtForceNameKeyReleased

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        File logo = media.SelectImage( prefs.get("LastOpenLogo", ""), "Select Logo");
        try {
            if ( logo != null ) {
                prefs.put("LastOpenLogo", logo.getPath().toString());
                force.LogoPath = logo.getCanonicalPath();
                media.setLogo(lblLogo, logo);
            }
        } catch (IOException ex) {
            Media.Messager("Could not load Logo.");
            System.out.println(ex.getMessage());
        }
}//GEN-LAST:event_lblLogoMouseClicked

    private void btnImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagesActionPerformed
        dlgImageMgr img = new dlgImageMgr( null, force, imageTracker );
        if ( img.hasWork ) {
            img.setLocationRelativeTo(this);
            img.setVisible(true);
        }
    }//GEN-LAST:event_btnImagesActionPerformed

    private void cmbViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViewActionPerformed
        switch ( cmbView.getSelectedIndex() ) {
            case 0: force.setCurrentModel(new tbTotalWarfareSmall(force)); break;
            case 1: force.setCurrentModel(new tbBattleForce(force)); break;
            case 2: force.setCurrentModel(new tbChatInfo(force)); break;
        }
        force.RefreshBV();
    }//GEN-LAST:event_cmbViewActionPerformed

    private void cmbUnitTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnitTypeActionPerformed
        switch ( cmbUnitType.getSelectedIndex() ) {
            case 0: force.setType(BattleForce.InnerSphere); break;
            case 1: force.setType(BattleForce.Clan); break;
            case 2: force.setType(BattleForce.Comstar); break;
        }
    }//GEN-LAST:event_cmbUnitTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnClearForce;
    private javax.swing.JButton btnAddMech;
    private javax.swing.JButton btnAmmoChooser;
    private javax.swing.JButton btnExportMTFs;
    private javax.swing.JButton btnExportMUL;
    private javax.swing.JButton btnImages;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPreview;
    private javax.swing.JButton btnPrintForce;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveUnit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbUnitType;
    private javax.swing.JComboBox cmbView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JLabel lblForceName;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTotalBV;
    private javax.swing.JLabel lblTotalTons;
    private javax.swing.JLabel lblTotalUnits;
    private javax.swing.JScrollPane spnList;
    private javax.swing.JTable tblForce;
    private javax.swing.JToolBar tlbActions;
    private javax.swing.JTextField txtForceName;
    private javax.swing.JTextField txtGunnery;
    private javax.swing.JTextField txtPiloting;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the force
     */
    public Force getForce() {
        return force;
    }

    /**
     * @param force the force to set
     */
    public void setForce(Force force) {
        this.force = force;
    }

}
